swagger: "2.0"
info:
  version: "0.0.1"
  title: "<Cisco UCS Manager Service>"

definitions:
  AuthInfo:
    description: "Authenticaion info for a request"
    properties:
      host:
        type: string
      user:
        type: string
      password:
        type: string
    required:
    - host
paths:
  /login:
    get:
      tags:
      - "default"
      description: "Gets a session cookie by logging into \nthe UCS Manager\n"
      operationId: "controllers.ucs_controller.login_get"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful login"
      x-tags:
      - tag: "default"
  /sys:
    get:
      tags:
      - "default"
      description: "Discover USC managed objects"
      operationId: "controllers.ucs_controller.systemGetAll"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful data fetch"
      x-tags:
      - tag: "default"
  /rackmount:
    get:
      tags:
      - "default"
      description: "Discover USC managed rackmount servers"
      operationId: "controllers.ucs_controller.getRackmount"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful data fetch of rackmount"
      x-tags:
      - tag: "default"
  /catalog:
    get:
      tags:
      - "default"
      description: "Returns a catalog of rackmount servers"
      operationId: "controllers.ucs_controller.getCatalog"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      - name: "identifier"
        in: "query"
        description: "UCS element dn"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful data fetch of rackmount catalogs"
      x-tags:
      - tag: "default"
  /pollers:
    get:
      tags:
      - "default"
      description: "Returns a dict which contains pollers information with specified classIds"
      operationId : "controllers.ucs_controller.getPollers"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "UCS manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      - name: "identifier"
        in: "query"
        description: "UCS node identifier"
        required: true
        type: "string"
      - name: "classIds"
        in: "query"
        description: "UCS class id array"
        required: true
        type: "array"
        items:
          type: "string"
      responses:
        200:
          description: "Successful data fetch of catalogs by class id"
      x-tags:
      - tag: "default"
  /pollers/async:
    get:
      tags:
      - "default"
      description: "Get pollers information asynchronously" 
      operationId: "controllers.ucs_async_controller.getPollersAsync"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      - name: "callbackId"
        in: "query"
        description: "Callback API identity"
        required: true
        type: "string"
      - name: "identifier"
        in: "query"
        description: "UCS node identifier"
        required: true
        type: "string"
      - name: "classIds"
        in: "query"
        description: "UCS class id array"
        required: true
        type: "array"
        items:
          type: "string"
      responses:
        202:
          description: "Accept data request"
      x-tags:
      - tag: "default"
  /chassis:
    get:
      tags:
      - "default"
      description: "Returns a catalog of rackmount servers"
      operationId: "controllers.ucs_controller.getChassis"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful data fetch of rackmount catalogs"
      x-tags:
      - tag: "default"
  /serviceProfile:
    get:
      tags:
      - "default"
      description: "Returns an array of Service Profiles"
      operationId: "controllers.ucs_controller.getServiceProfile"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful data fetch of Service Profiles"
      x-tags:
      - tag: "default"
  /power:
    post:
      tags:
      - "default"
      description: "Provide power mgmt capabilities for ucs service profiles"
      operationId: "controllers.ucs_controller.powerMgmt"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      - name: "identifier"
        in: "query"
        description: "dn of the ucs element or the dn for the service profile"
        required: false
        type: "string"
      - name: "action"
        in: "query"
        description: "power action to be taken. Could be 'on', 'off', 'cycle-wait', 'cycle-immediate',
        'bmc-reset-immediate', 'ipmi-reset', 'hard-reset-immediate', 'soft-shut-down' "
        required: false
        type: "string"
      - name: "physical"
        in: "query"
        description: "if true send the power command to the physical server, false use the associated logical server"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Succesfully posted the power action"
      x-tags:
      - tag: "default"
    get:
      tags:
      - "default"
      description: "Return power status of ucs element"
      operationId: "controllers.ucs_controller.powerStatus"
      parameters:
      - name: "ucs-host"
        in: "header"
        description: "USC manager host name or IP"
        required: true
        type: "string"
      - name: "ucs-user"
        in: "header"
        description: "UCS manager user name"
        required: true
        type: "string"
      - name: "ucs-password"
        in: "header"
        description: "UCS manager user password"
        required: true
        type: "string"
      - name: "identifier"
        in: "query"
        description: "dn of the ucs element or the dn for the service profile"
        required: false
        type: "string"
      responses:
        200:
          description: "Successfully fetched the power status for the ucs element"
      x-tags:
      - tag: "default"
